# BASIC PYTHON

# 1.Split the String

In [19]:
# s = "Hi there Sam!"

In [36]:
str = "Hi there Sam!"
split=str.split()
print(split)

['Hi', 'there', 'Sam!']


# 2. Use .format() to print the following string.
# Output should be: The diameter of Earth is 12742 kilometers.

In [21]:
planet = "Earth"
diameter = 12742

In [22]:
planet = "Earth"
diameter = 12742
text="The diameter of {0} is {1} kilometers".format(planet,diameter)
print(text)

The diameter of Earth is 12742 kilometers


# 3. In this nest dictionary grab the word "hello"

In [37]:
data = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [39]:
data= {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(data['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [40]:
import numpy as np

# 4.1 Create an array of 10 zeros?

# 4.2 Create an array of 10 fives?

In [47]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 5. Create an array of all the even integers from 20 to 35

In [49]:
import numpy as np
array=np.arange(10)*5
print(array)

[ 0  5 10 15 20 25 30 35 40 45]


# 6. Create a 3x3 matrix with values ranging from 0 to 8

In [50]:
import numpy as np
array = np.arange(0, 9).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 7. Concatinate a and b

# a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [51]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
array1= np.concatenate((a, b))
print(array1)

[1 2 3 4 5 6]


# Pandas

# 8. Create a dataframe with 3 rows and 2 columns

In [52]:
import pandas as pd

In [54]:
import pandas as pd
data = [['Ben', 20, 'M'], ['john', 25, 'M']]
dat = pd.DataFrame(data, index=[1, 2], columns=['Name', 'Age', 'Gender'])
print(dat)

   Name  Age Gender
1   Ben   20      M
2  john   25      M


# 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [55]:
import pandas as pd
date = pd.date_range(start='1/1/2023', end='10/2/2023')
print(date)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


# 10. Create 2D list to DataFrame

In [56]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [57]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lists1 = pd.DataFrame(lists)
print(lists1)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
