In [8]:
s = "Hi there Sam!"

In [9]:
s = "Hi there Sam!"
split=s.split()
print(split)

['Hi', 'there', 'Sam!']


In [10]:
planet = "Earth"
diameter = 12742

In [11]:
planet = "Earth"
diameter = 12742
text="The diameter of {0} is {1} kilometers".format(planet,diameter)
print(text)

The diameter of Earth is 12742 kilometers


In [12]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [13]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [14]:
import numpy as np

In [15]:
import numpy as np
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
import numpy as np
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [22]:
import numpy as np
arr=np.arange(10)*5
print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [23]:
import numpy as np
arr = np.arange(0, 9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
array = np.concatenate((a, b))
print(array)

[1 2 3 4 5 6]


In [25]:
import pandas as pd

In [26]:
import pandas as pd
data = [['Ben', 20, 'M'], ['john', 25, 'M']]
dat = pd.DataFrame(data, index=[1, 2], columns=['Name', 'Age', 'Gender'])
print(dat)

   Name  Age Gender
1   Ben   20      M
2  john   25      M


In [29]:
import pandas as pd
date = pd.date_range(start='1/1/2023', end='10/2/2023')
print(date)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


In [30]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [31]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lists1 = pd.DataFrame(lists)
print(lists1)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
